// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8VFdNkiZCneoQgs52DkC1uQp8cpJyiOs',
    appId: '1:196484785411:web:21d46281f021526b117536',
    messagingSenderId: '196484785411',
    projectId: 'aifinancaltracker',
    authDomain: 'aifinancaltracker.firebaseapp.com',
    storageBucket: 'aifinancaltracker.firebasestorage.app',
    measurementId: 'G-LX6PBEMQS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdlLc59f6ped8ikbyd0xGMpdOBNDzjuA',
    appId: '1:196484785411:android:8015f27c6107689d117536',
    messagingSenderId: '196484785411',
    projectId: 'aifinancaltracker',
    storageBucket: 'aifinancaltracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClvD166cpIJxBaCAloIQVpD-okEGcbxw0',
    appId: '1:196484785411:ios:a668dcd6b9aa508b117536',
    messagingSenderId: '196484785411',
    projectId: 'aifinancaltracker',
    storageBucket: 'aifinancaltracker.firebasestorage.app',
    iosBundleId: 'com.example.mindfulCurator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClvD166cpIJxBaCAloIQVpD-okEGcbxw0',
    appId: '1:196484785411:ios:a668dcd6b9aa508b117536',
    messagingSenderId: '196484785411',
    projectId: 'aifinancaltracker',
    storageBucket: 'aifinancaltracker.firebasestorage.app',
    iosBundleId: 'com.example.mindfulCurator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8VFdNkiZCneoQgs52DkC1uQp8cpJyiOs',
    appId: '1:196484785411:web:61226fe2e2467b62117536',
    messagingSenderId: '196484785411',
    projectId: 'aifinancaltracker',
    authDomain: 'aifinancaltracker.firebaseapp.com',
    storageBucket: 'aifinancaltracker.firebasestorage.app',
    measurementId: 'G-3HRQ7S8JJT',
  );

}